import express from 'express';
import authRoutes from './modules/Auth/routes/auth';
import externalRoutes from './modules/External/routes/external';
import notificationsRoutes from './modules/Notification/routes/notifications';
import auditRoutes from './modules/Audit/routes/audit';
import usersRoutes from './modules/User/routes/users';
import employeesRoutes from './modules/Employee/routes/employees';
import jobRolesRoutes from './modules/Employee/routes/job-roles';
import materialsRoutes from './modules/Material/routes/materials';
import servicesRoutes from './modules/Service/routes/services';
import workAreasRoutes from './modules/WorkArea/routes/work-areas';
import peopleRoutes from './modules/People/routes/people';
import serviceOrdersRoutes from './modules/ServiceOrder/routes/service-orders';
import qualityControlsRoutes from './modules/QualityControl/routes/quality-controls';
import settingsRoutes from './modules/Settings/routes/settings';
import groupsRoutes from './modules/User/routes/groups';
import financeRoutes from './modules/Finance/routes/finance';
import stockRoutes from './modules/Stock/routes/stock';
import dashboardRoutes from './modules/Dashboard/routes/dashboard';
import reportsRoutes from './modules/Reports/routes/reports';

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/external', externalRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/audit', auditRoutes);
router.use('/users', usersRoutes);
router.use('/employees', employeesRoutes);
router.use('/job-roles', jobRolesRoutes);
router.use('/materials', materialsRoutes);
router.use('/services', servicesRoutes);
router.use('/work-areas', workAreasRoutes);
router.use('/people', peopleRoutes);
router.use('/service-orders', serviceOrdersRoutes);
router.use('/quality-controls', qualityControlsRoutes);
router.use('/settings', settingsRoutes);
router.use('/groups', groupsRoutes);
router.use('/finance', financeRoutes);
router.use('/stock', stockRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/reports', reportsRoutes);

export default router;
