ALTER TABLE "ServiceOrder"
ADD COLUMN IF NOT EXISTS "workCenter" TEXT,
ADD COLUMN IF NOT EXISTS "plannedStartDate" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "plannedEndDate" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "plannedHours" DOUBLE PRECISION;
