import express from 'express';
import usersRoutes from './routes/users';
import employeesRoutes from './routes/employees';
import jobRolesRoutes from './routes/job-roles';
import materialsRoutes from './routes/materials';
import servicesRoutes from './routes/services';
import workAreasRoutes from './routes/work-areas';
import peopleRoutes from './routes/people';
import serviceOrdersRoutes from './routes/service-orders';
import qualityControlsRoutes from './routes/quality-controls';
import settingsRoutes from './routes/settings';
import groupsRoutes from './routes/groups';
import financeRoutes from './routes/finance';
import stockRoutes from './routes/stock';
import dashboardRoutes from './routes/dashboard';
import reportsRoutes from './routes/reports';
import authRoutes from './routes/auth';
import externalRoutes from './routes/external';

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/external', externalRoutes);
router.use('/users', usersRoutes);
router.use('/employees', employeesRoutes);
router.use('/job-roles', jobRolesRoutes);
router.use('/materials', materialsRoutes);
router.use('/services', servicesRoutes);
router.use('/work-areas', workAreasRoutes);
router.use('/people', peopleRoutes);
router.use('/service-orders', serviceOrdersRoutes);
router.use('/quality-controls', qualityControlsRoutes);
router.use('/settings', settingsRoutes);
router.use('/groups', groupsRoutes);
router.use('/finance', financeRoutes);
router.use('/stock', stockRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/reports', reportsRoutes);

export default router;
